force-app/main/default/objects/Reading__c/Reading__c.object-meta.xml
<CustomObject>
    <description>A reading of an extract from their (typically new) book by an author.</description>
    <label>Reading</label>
    <nameField>
        <label>Reading Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Readings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Reading__c/fields/Author__c.field-meta.xml
<CustomField>
    <fullName>Author__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>The author carrying out the reading.</description>
    <label>Author</label>
    <referenceTo>Author__c</referenceTo>
    <relationshipLabel>Readings</relationshipLabel>
    <relationshipName>Readings</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Reading__c/fields/Book__c.field-meta.xml
<CustomField>
    <fullName>Book__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The book that an extract will be read from.</description>
    <label>Book</label>
    <referenceTo>Book__c</referenceTo>
    <relationshipLabel>Readings</relationshipLabel>
    <relationshipName>Readings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/ReadingService.cls
public inherited sharing class ReadingService {
    public List<Reading__c> searchReadings(Id authorId, String genre)
    {
        String queryStr='select Id, Name, Starts__c, Ends__c, Author__r.Name, Book__r.Name, Book__r.Genre__c from Reading__c ';

        String whereClause='';

        if (null!=authorId)
        {
            if (''!=whereClause)
            {
                whereClause+=' AND ';
            }
            whereClause+=' Book__r.Author__c=:authorId ';
        }

        if (!String.isBlank(genre))
        {
            if (''!=whereClause)
            {
                whereClause+=' AND ';
            }
            whereClause+=' Book__r.Genre__c=:genre ';
        }

        if (''!=whereClause)
        {
            queryStr+=' WHERE ' + whereClause;
        }

        List<Reading__c> readings=Database.query(queryStr);
        return readings;
    }
}